### PR TITLE
add --delete-timeout for deleting FTP files after a configurable timeout in seconds

### PR DESCRIPTION
**Pull request by danleyb2**

### CODE REVIEW

**Review by marcbelmont — COMMENTED** [review]
- [ ] Instead of having two separate branches for --delete-timeout or simple delete. Let's make the default delete have a timeout of 0 seconds. That will make the code simpler.
- [ ] Instead of using a global, how about we just look at the file creation date. If it is too old, delete it.

**Comment by danleyb2** [comment]
@marcbelmont Had also thought of using the file modified time at first but this would have the following issues

1. - it requires switching to the FTP command **MLSD** that will allow retrieving the extra metadata(modify-timestamp) .
the current command only retrieves the filename. so i thought there might be a perfomance issue if we retrieve the extra  metadata severally only to compare the timestamp and this would have to be done for all the files. 

2. - on first run, all files would be deleted. It only becomes efective on new files after a few runs

overally, it's easier to implement using the file creation date so i am able to switch to that if the above won't be an issue

**Comment by marcbelmont** [comment]
file creation date is ok.

**Comment by danleyb2** [comment]
Please Review the new implementation here
https://github.com/marcbelmont/deep-license-plate-recognition/pull/33

**Pull request closed without merging**
